/*
 * Country Code Lookup API
 * API for conversion country code to country name from remote API https://www.travel-advisory.info/api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.vb.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Remote Api status JSON file format.
 */
@ApiModel(description = "Remote Api status JSON file format.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-10-24T21:02:39.389-07:00")
public class RemoteApiStatusApiStatus   {
  @JsonProperty("code")
  private Integer code = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("cache")
  private String cache = null;

  @JsonProperty("note")
  private String note = null;

  @JsonProperty("count")
  private Integer count = null;

  public RemoteApiStatusApiStatus code(Integer code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   **/
  @JsonProperty("code")
  @ApiModelProperty(value = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public RemoteApiStatusApiStatus status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public RemoteApiStatusApiStatus cache(String cache) {
    this.cache = cache;
    return this;
  }

  /**
   * Get cache
   * @return cache
   **/
  @JsonProperty("cache")
  @ApiModelProperty(value = "")
  public String getCache() {
    return cache;
  }

  public void setCache(String cache) {
    this.cache = cache;
  }

  public RemoteApiStatusApiStatus note(String note) {
    this.note = note;
    return this;
  }

  /**
   * Get note
   * @return note
   **/
  @JsonProperty("note")
  @ApiModelProperty(value = "")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public RemoteApiStatusApiStatus count(Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
   **/
  @JsonProperty("count")
  @ApiModelProperty(value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteApiStatusApiStatus remoteApiStatusApiStatus = (RemoteApiStatusApiStatus) o;
    return Objects.equals(this.code, remoteApiStatusApiStatus.code) &&
        Objects.equals(this.status, remoteApiStatusApiStatus.status) &&
        Objects.equals(this.cache, remoteApiStatusApiStatus.cache) &&
        Objects.equals(this.note, remoteApiStatusApiStatus.note) &&
        Objects.equals(this.count, remoteApiStatusApiStatus.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, status, cache, note, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteApiStatusApiStatus {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    cache: ").append(toIndentedString(cache)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

